### ISSUE TITLE
Allow easier searching of measures

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-device-manager#130]
## Description

Measures history are only accessible through Kuzzle standard API and ES query language.

It would be more convenient to have a high level API to retrieve a range of measure documents: `assets/<assetId>/measures?start=12345&end=54321`

:warning: Since this is possible through the standard query language, we need to discuss first if this is really needed because it will add more code to do something already possible before

**Comment by jpdalbi** [comment]
in the 2-dev version it is possible to find a mesure between two dates. However with the data model it would be interesting to have filter on the type or on the name of the measure. 
Find measures between two dates of position type.

**Comment by Aschen** [comment]
@jpdalbi This is actually possible with a raw ES query but I will suggest to add those parameters in this high level API action as well :+1:

**Comment by Aschen** [comment]
This is not very useful because `document:search` on `measures` collection already allows to do that
