### ISSUE TITLE
Configuration catalog for downlink

### ISSUE THREAD

**Issue by Aschen** [kuzzleio/kuzzle-device-manager#14]
Build and save a configuration catalog to send downlink to sensors

Ideally we could develop an API adapter to one of the platform (e.g. SPOT) to automatize the sent of downlinks with workflows:
 - I enter a platform area: send downlink to reduce the frequency of GPS data and use Wifi instead

**Comment by jpdalbi** [comment]
it could be interesting to generalize this feature to a configuration sent to a device. I use devices configured with a json payload. It will be also interesting to have the result of the operation (success, failure) and to have last successful configuration. Today i use metadata of asset to do that.

**Comment by Aschen** [comment]
That's something we are planning in the roadmap but first we need to integrate with platforms like LiveObject or TheThingsNetwork
