### ISSUE TITLE
Plugin compilation errors because of direct GitHub dependency

### ISSUE THREAD

**Issue by UncleSamSwiss** [kuzzleio/kuzzle-device-manager#141]
@Aschen We are using device manager 0.4.7, unfortunately due to the [changes ](https://github.com/kuzzleio/kuzzle-plugin-commons/commit/d8d6893db20a660b4565bb6ce12fa7789fcfac08) you did over the weekend, the application using the device manager doesn't compile anymore on our build system:
```
node_modules/@kuzzleio/plugin-device-manager/lib/core-classes/DeviceManagerEngine.d.ts:6:50 - error TS2314: Generic type 'AbstractEngine<TPlugin>' requires 1 type argument(s).

6 export declare class DeviceManagerEngine extends AbstractEngine {
```

This seems to be due to the direct dependency of device manager from `kuzzleio/kuzzle-plugin-commons` by direct GitHub link.

Since you updated master on GitHub, this now fails our builds. It only happens on the build system as we always do a clean `npm install` without an existing `node_modules` directory.

Currently I'm not even sure how to fix this to have a running build again.

**Comment by UncleSamSwiss** [comment]
Well, I found a (very ugly) workaround:

1. I need to add a dependency to my project:
```json
  "dependencies": {
    ...
    "kuzzle-plugin-commons": "git+https://github.com/kuzzleio/kuzzle-plugin-commons.git#c801ccc"
  },
```
2. Then I need to call the following command immediately after `npm install`:
```bash
rm -rf node_modules/@kuzzleio/plugin-device-manager/node_modules/
```

Ouch 😒

**Comment by Aschen** [comment]
Hello @UncleSamSwiss ,

We the Device Manager was not open source, we adopted this temporary solution of having this repo containing common classes for our plugins.  
This solution is not suitable anymore since the Device Manager is now on an industrial release management process.

We will publish those classes on NPM and use semver like every other products we are maintaining :+1: 

I will update this issue when it's done.

Thanks you for your feedback !

**Comment by Aschen** [comment]
Fixed in https://github.com/kuzzleio/kuzzle-device-manager/releases/tag/0.4.8

**Comment by UncleSamSwiss** [comment]
Can you please also publish the npm package for kuzzle-device-manager. On GitHub packages it is still 0.4.7:
https://github.com/kuzzleio/kuzzle-device-manager/packages/982449

```
$ npm i
npm ERR! code ETARGET
npm ERR! notarget No matching version found for @kuzzleio/plugin-device-manager@^0.4.8.
```

**Comment by Aschen** [comment]
It has been fixed by publishing the device manager only on NPM: https://www.npmjs.com/package/kuzzle-device-manager

**Comment by Aschen** [comment]
You will need to use the 0.4.9, the previous version was published without the built files
