### ISSUE TITLE
Clarify id of catalog entry (and device)

### ISSUE THREAD

**Issue by UncleSamSwiss** [kuzzleio/kuzzle-device-manager#143]
I couldn't find anywhere in the [provisioning documentation](https://github.com/kuzzleio/kuzzle-device-manager/blob/master/doc/1/guides/provisioning/index.md) any mention that the catalog entry must have an exact ID:
https://github.com/kuzzleio/kuzzle-device-manager/blob/41582f8fc3c0ab0b1b381a3e8635e340d463a2d5/lib/core-classes/PayloadService.ts#L204

Please clarify that the ID must always be `catalog--<device-id>`.

Also, it is quite difficult to figure out that the device ID **must** always be `<model>-<reference>`. The only vague mention is here:
https://github.com/kuzzleio/kuzzle-device-manager/blob/41582f8fc3c0ab0b1b381a3e8635e340d463a2d5/doc/1/guides/devices/index.md#L15

(@Aschen: re our talk yesterday)

**Comment by Aschen** [comment]
Thanks for your feedback :+1: 

The catalog entry have this format because it's more readable but it shouldn't be mandatory, I will update the code accordingly.

About the device ID, why do you say it must be that format?

**Comment by UncleSamSwiss** [comment]
Thanks for the update.

The device ID is hardcoded as well:
https://github.com/kuzzleio/kuzzle-device-manager/blob/3a304a50c1f50f4353024d199878d6f2581d77c9/lib/models/Device.ts#L10

And the above constructor is called here (without a second argument):
https://github.com/kuzzleio/kuzzle-device-manager/blob/3a304a50c1f50f4353024d199878d6f2581d77c9/lib/core-classes/PayloadService.ts#L85

**Comment by Aschen** [comment]
Oh yes sorry I misread, I thought you were talking about assets IDs :facepalm: 

I will submit an issue to update the documentation and make this clear :+1:

**Comment by Aschen** [comment]
Catalog has been removed for simple provisioning through device creation in v2
