### ISSUE TITLE
[doc] Wrong example for DeviceMappingsManager.registerMeasure()

### ISSUE THREAD

**Issue by UncleSamSwiss** [kuzzleio/kuzzle-device-manager#161]
For me the following code doesn't work:

https://github.com/kuzzleio/kuzzle-device-manager/blob/5812b9f1e6feb4e4d4f993991a30fa4282217ec0/doc/1/classes/devices-custom-properties/register-measure/index.md?plain=1#L38-L61

I needed to do something similar to this:
```js
 deviceManagerPlugin.devices.registerMeasure( 
   'temperature', 
   { 
     fahrenheit: { type: 'float' }, 
     celsius: { type: 'float' } 
   }); 
```

In addition to the different hierarchical position of the properties (no `properties`) the third argument doesn't exist on the method (any more):
https://github.com/kuzzleio/kuzzle-device-manager/blob/5812b9f1e6feb4e4d4f993991a30fa4282217ec0/lib/core-classes/DeviceMappingsManager.ts#L56

**Comment by UncleSamSwiss** [comment]
Also this document seems to have the same mistake:

https://github.com/kuzzleio/kuzzle-device-manager/blob/c81198fd2b44d9db3b2a19fafd6681e1e2efdd8b/doc/1/guides/mappings/index.md?plain=1#L198-L209

**Comment by Aschen** [comment]
Hello @UncleSamSwiss 

Thanks for pointing this mistake. We are currently working on the plugin v2 which will improve this part
