### ISSUE TITLE
lost measure name in asset when receiving a payload

### ISSUE THREAD

**Issue by jpdalbi** [kuzzleio/kuzzle-device-manager#172]
Device is linked to an asset with measuresNAmes set to specific values: {"position": "pos1", "movement": "mov1"}. The asset is correctly modified with the measures ans the new names.
when un paylaod is send by a push API on the decoder, the measures looses the name in the asset.

**Comment by Aschen** [comment]
Fixed in https://github.com/kuzzleio/kuzzle-device-manager/pull/183
