### ISSUE TITLE
measures erased in an asset when receiving a payload

### ISSUE THREAD

**Issue by jpdalbi** [kuzzleio/kuzzle-device-manager#173]
Two devices are enroled with 3 measures (position, movement, battery) each. An asset is created. The first device is linked with measures names specific, the second device  with default names. 
The asset is updated with 6 measures with the correct names.
When pushing a payload for first device on decoder via API, the asset contains only the three measures of the device. The other measures are erased.

**Comment by Aschen** [comment]
Fixed in https://github.com/kuzzleio/kuzzle-device-manager/pull/183
