### ISSUE TITLE
Automatic names for devices and Assets

### ISSUE THREAD

**Issue by jpdalbi** [kuzzleio/kuzzle-device-manager#174]
When a device is created automatically the is made with deviceModel and deviceReference separated by hyphen (AbeewayITSpot-deveui001). It was undescore in the prévious version.
When an asset is create it is an undescore wich separate type, model reference (CaisseMobile_krone_0008)

**Comment by jpdalbi** [comment]
In fact when we create an asset directly with device-manager/asset:create the name is made with type-model-reference, separated by hyphen. In the above comment the name was created with _id and a local naming. So there is not a consistency problem the separator is hyphen.

**Comment by Aschen** [comment]
You should use the provided API to create assets and devices, they will compute the name with hyphen separator automatically :+1:
