### ISSUE TITLE
inconsistency between the device model and a decoder

### ISSUE THREAD

**Issue by jpdalbi** [kuzzleio/kuzzle-device-manager#175]
A device exists with a device model AbeewayITSpot2. The decoder is modified and now is for model AbeewayITSpot. 
It is possible to link this device to an asset without error. In the former version an error was thrown: TypeError: Cannot read property 'copyToAsset' of undefined which means that the device model was not in the list of decoders.

**Comment by Aschen** [comment]
Note: I'm not sure how to handle renaming of decoders. Maybe providing an utility action to migrate devices (the decoder model is part of the device ID)

**Comment by Aschen** [comment]
@jpdalbi Is this still an issue?
