### ISSUE TITLE
Ensure Epoch Millis for `measuredAt` in measures

### ISSUE THREAD

**Issue by jpdalbi** [kuzzleio/kuzzle-device-manager#185]
In measures createdAt is in epoch milliseconds, measuredAt in epoch seconds (v2 RC3 version).  
Could be simpliest to have time in Epoch ms?

EDIT (Aschen)

The plugin should ensure that measuredAt is alway an ms timestamp

**Comment by Aschen** [comment]
Yes it's a good idea :+1:

**Comment by jpdalbi** [comment]
In fact in the payload of the sensor the time was an epoch in seconds. It was written directly in measuredAt it remains in seconds.

**Comment by Aschen** [comment]
Hmm actually it's the user that decide how the time is decoded from the payload so you should provide it in ms right.

But the plugin should ensure that `measuredAt` is alway an ms timestamp :+1:

**Comment by Aschen** [comment]
has been done
