### ISSUE TITLE
Measure battery in integer 

### ISSUE THREAD

**Issue by jpdalbi** [kuzzleio/kuzzle-device-manager#192]
when a request less than is donne on battery level, an asset with a battery level of 4.011 is returned with a level value of 4.01 in the request
<img width="367" alt="Capture d’écran 2022-06-01 à 18 00 24" src="https://user-images.githubusercontent.com/16255802/171448641-d6a449f9-1551-4a7a-ac70-884171933c74.png">
The mapping of battery value is integer, it should be float?

**Comment by Aschen** [comment]
The battery level is supposed to be a percentage between 0 and 100 and not the voltage. 

The measure could be updated to include the original voltage as a float :+1:
