### ISSUE TITLE
Define name of mesure type in its definition, not at registering

### ISSUE THREAD

**Issue by ChillPC** [kuzzleio/kuzzle-device-manager#215]
Instead of having :
```ts
    this.measures.register('temperature', temperatureMeasure);
```
Have simply:
```ts
    this.measures.register(temperatureMeasure);
```
With `'temperature'` defined in its file with the mappings and the unit

**Comment by Aschen** [comment]
Actually the type of the `register` method is only used to ensure that we don't register twice the same measure, then the `type` of a measurement should be set inside the decoder:
 - https://github.com/kuzzleio/kuzzle-device-manager/blob/2-stable/features/fixtures/application/decoders/DummyTempDecoder.ts#L37
 - https://github.com/kuzzleio/kuzzle-device-manager/blob/2-stable/lib/core-classes/MeasureService.ts#L208
