### ISSUE TITLE
How to handle devices online via MQTT

### ISSUE THREAD

**Issue by xdien** [kuzzleio/kuzzle-device-manager#324]
Hello kuzzle
- I'm developing a feature to identify `online` devices. My device connects to kuzzle using MQTT and the `keep alive` option.
- Where do I start in kuzzle to gradually process it as a `measure` or another definition to handle this?

Thank you

**Comment by Juiced66** [comment]
> Where do I start in kuzzle to gradually process it as a measure or another definition to handle this?

You could use [memoryStorage](https://docs.kuzzle.io/core/2/api/controllers/memory-storage/setex/) to keep track of devices that have polled and [ask](https://docs.kuzzle.io/core/2/api/controllers/memory-storage/ttl/) whenever you want 

It could be triggered by a pipe on `"device-manager:measures:process:after"`

**Comment by xdien** [comment]
Thank you.
I will try it
